"""Cuckoo-cycle (Cuckatoo-style) witness search at toy size.

Edges of a bipartite graph are generated by SipHash-2-4 keyed with BLAKE2b(header || nonce);
a proof is a cycle of length ``L`` (42 for Grin); the witness is the sorted list of its edge
indices, which is what Grin's Stratum ``submit`` carries (``pow: Vec<u64>``, see
docs/PHASE7_ASIC_SEARCH.md). Real Cuckatoo32 has 2**32 edges and a Grin-specific SipHash
variant; this toy uses standard SipHash-2-4 (checked against the reference test vector) and
small graphs. The expected number of L-cycles per random graph is ~1/L, independent of size.
"""

from __future__ import annotations

import hashlib
import struct
from dataclasses import dataclass

import numpy as np

M64 = np.uint64(0xFFFFFFFFFFFFFFFF)


def _rotl(x: np.ndarray, b: int) -> np.ndarray:
    return (x << np.uint64(b)) | (x >> np.uint64(64 - b))


def siphash24(k0: int, k1: int, m: np.ndarray) -> np.ndarray:
    """Standard SipHash-2-4 of one 8-byte little-endian word per element (vectorized)."""
    m = np.asarray(m, np.uint64)
    v0 = np.full(m.shape, np.uint64(k0 ^ 0x736F6D6570736575), np.uint64)
    v1 = np.full(m.shape, np.uint64(k1 ^ 0x646F72616E646F6D), np.uint64)
    v2 = np.full(m.shape, np.uint64(k0 ^ 0x6C7967656E657261), np.uint64)
    v3 = np.full(m.shape, np.uint64(k1 ^ 0x7465646279746573), np.uint64)

    def rnd(v0, v1, v2, v3):
        v0 = v0 + v1; v1 = _rotl(v1, 13); v1 ^= v0; v0 = _rotl(v0, 32)
        v2 = v2 + v3; v3 = _rotl(v3, 16); v3 ^= v2
        v0 = v0 + v3; v3 = _rotl(v3, 21); v3 ^= v0
        v2 = v2 + v1; v1 = _rotl(v1, 17); v1 ^= v2; v2 = _rotl(v2, 32)
        return v0, v1, v2, v3

    b = np.uint64(8 << 56)
    v3 ^= m
    v0, v1, v2, v3 = rnd(v0, v1, v2, v3)
    v0, v1, v2, v3 = rnd(v0, v1, v2, v3)
    v0 ^= m
    v3 ^= b
    v0, v1, v2, v3 = rnd(v0, v1, v2, v3)
    v0, v1, v2, v3 = rnd(v0, v1, v2, v3)
    v0 ^= b
    v2 ^= np.uint64(0xFF)
    for _ in range(4):
        v0, v1, v2, v3 = rnd(v0, v1, v2, v3)
    return v0 ^ v1 ^ v2 ^ v3


@dataclass
class CuckooResult:
    edges_u: np.ndarray
    edges_v: np.ndarray
    cycles: list[list[int]]  # sorted edge indices of each cycle of the requested length
    cycle_lengths: list[int]  # lengths of all cycles closed while building (diagnostics)


def cuckoo_graph(header: bytes, nonce: int, edge_bits: int) -> tuple[np.ndarray, np.ndarray]:
    key = hashlib.blake2b(header + struct.pack("<Q", nonce), digest_size=16).digest()
    k0, k1 = struct.unpack("<QQ", key)
    n = 1 << edge_bits
    i = np.arange(n, dtype=np.uint64)
    mask = np.uint64(n - 1)
    with np.errstate(over="ignore"):
        u = siphash24(k0, k1, 2 * i) & mask
        v = siphash24(k0, k1, 2 * i + np.uint64(1)) & mask
    return u.astype(np.int64), v.astype(np.int64)


def find_cycles(header: bytes, nonce: int, edge_bits: int = 14, length: int = 42) -> CuckooResult:
    u, v = cuckoo_graph(header, nonce, edge_bits)
    n = 1 << edge_bits
    parent = list(range(2 * n))  # U nodes 0..n-1, V nodes n..2n-1

    def find(x: int) -> int:
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    adj: dict[int, list[tuple[int, int]]] = {}
    cycles, lengths = [], []
    for e in range(n):
        a, b = int(u[e]), int(v[e]) + n
        ra, rb = find(a), find(b)
        if ra == rb:  # closes a cycle: path a..b in the current forest + this edge
            prev = {a: (None, None)}
            stack = [a]
            while stack and b not in prev:
                x = stack.pop()
                for y, ei in adj.get(x, []):
                    if y not in prev:
                        prev[y] = (x, ei)
                        stack.append(y)
            path = []
            x = b
            while prev.get(x, (None, None))[0] is not None:
                px, ei = prev[x]
                path.append(ei)
                x = px
            L = len(path) + 1
            lengths.append(L)
            if L == length:
                cycles.append(sorted(path + [e]))
            continue  # keep the graph a forest (Cuckoo solvers do the same for the union-find view)
        parent[ra] = rb
        adj.setdefault(a, []).append((b, e))
        adj.setdefault(b, []).append((a, e))
    return CuckooResult(u, v, cycles, lengths)
